name: release
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: new
    steps:
      - uses: actions/checkout@v3
      - run: echo "$env_key" > ./server/.env && ./make.sh
        env: 
          env_key: ${{ secrets.ENV }}
