name: release
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: echo "$env_key" > .env && ./make.sh
      - env: 
          env_key: ${{ secrets.ENV }}
