name: release
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - env:
        env_key: ${{ secrets.ENV }}}
      - run: echo "$env_key" > .env
      - run: ./make.sh
